// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"myblog/internal/biz"
	"myblog/internal/conf"
	"myblog/internal/data"
	"myblog/internal/server"
	"myblog/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	articleRepo := data.NewArticleRepo(dataData)
	articleUsecase := biz.NewArticleUsecase(articleRepo)
	blogService := service.NewBlogService(articleUsecase)
	httpServer := server.NewHTTPServer(confServer, logger, blogService)
	grpcServer := server.NewGRPCServer(confServer, logger, blogService)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
	}, nil
}
